src/chapter6/beans/Coment.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class Coment implements Serializable {
    private static final long serialVersionUID = 1L;

    private  int id;
    private  int userid;
    private int messageid;
    private  String text;
    private  Date created_date;
    private int is_deleted;
    private  String name;


	public  int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	public int getMessageid() {
		return messageid;
	}
	public void setMessageid(int messageid) {
		this.messageid = messageid;
	}
	public  String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public int getIs_deleted() {
		return is_deleted;
	}
	public void setIs_deleted(int is_deleted) {
		this.is_deleted = is_deleted;
	}

	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getUserid() {
		return userid;
	}
	public void setUserid(int userid) {
		this.userid = userid;
	}
	public String getStatusChangeLabel() {
		return is_deleted == 0 ? "削除" : "復活";
	}

}

src/chapter6/beans/User.java
package chapter6.beans;

import java.io.Serializable;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private String loginid;
    private String password;
    private String name;
    private int branch;
    private int position;
    private int is_stopped;
    private String checkpassword;
    private String branchname;
    private String positionname;
    private int positionid;
    private int branchid;


	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getLoginid() {
		return loginid;
	}
	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getBranch() {
		return branch;
	}
	public void setBranch(int branch) {
		this.branch = branch;
	}
	public int getPosition() {
		return position;
	}
	public void setPosition(int position) {
		this.position = position;
	}
	public int getIs_Stopped() {
		return is_stopped;
	}
	public void setIs_Stopped(int is_stopped) {
		this.is_stopped = is_stopped;
	}
	public String getCheckPassword() {
		return checkpassword;
	}
	public void setCheckPassword(String password) {
		this.password = checkpassword;
	}

	public String getStatusChangeLabel() {
		return is_stopped == 0 ? "停止" : "復活";
	}
	public String getBranchname() {
		return branchname;
	}
	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}
	public String getPositionname() {
		return positionname;
	}
	public void setPositionname(String positionname) {
		this.positionname = positionname;
}
	public int getPositionid() {
		return positionid;
	}
	public void setPositionid(int positionid) {
		this.positionid = positionid;
	}
	public int getBranchid() {
		return branchid;
	}
	public void setBranchid(int branchid) {
		this.branchid = branchid;
	}
	}

src/chapter6/controller/BoardServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.beans.User;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/board" })
public class BoardServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		User user = (User) request.getSession().getAttribute("loginUser");

		boolean isShowMessageForm;
		if (user != null) {
			isShowMessageForm = true;
		} else {
			isShowMessageForm = false;
		}

		List<Message> messages = new MessageService().getMessage();

		request.setAttribute("messages", messages);
		request.setAttribute("isShowMessageForm", isShowMessageForm);

		request.getRequestDispatcher("board.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		List<String> messages = new ArrayList<String>();

		if (isValid(request, messages) == true) {

			User user = (User) session.getAttribute("loginUser");

			Message message = new Message();
			message.setTitle(request.getParameter("title"));
			message.setText(request.getParameter("message"));
			message.setCategory(request.getParameter("category"));
			message.setUserid(user.getId());

			new MessageService().register(message);

			response.sendRedirect("./");
		} else {
			//エラー時に1つの項目しか表示されない
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("board");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String message = request.getParameter("message");
		String title = request.getParameter("title");
		String category = request.getParameter("category");

		if (StringUtils.isEmpty(title) == true) {
			messages.add("タイトルを入力してください");
			return false;
		} else if (!(title.matches("^.{1,30}$"))) {
			messages.add("タイトルは30文字以内で入力してください");
			return false;
		}
		if (StringUtils.isEmpty(message) == true) {
			messages.add("メッセージを入力してください");
			return false;
		} else if (1000 < message.length()) {
			messages.add("1,000文字以下で入力してください");
			return false;
		}
		if (StringUtils.isEmpty(category) == true) {
			messages.add("カテゴリーを入力してください");
			return false;
		} else if (!(category.matches("^.{1,10}$"))) {
			messages.add("カテゴリーは10文字以内で入力してください");
			return false;
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/chapter6/controller/ComentServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.LoginService;

@WebServlet(urlPatterns = { "/coment" })
public class ComentServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("coment.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		String loginid = request.getParameter("loginid");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		User user = loginService.login(loginid, password);

		if (user != null) {
			if (user.getIs_Stopped() != 1) {
				session.setAttribute("loginUser", user);
				response.sendRedirect("./");
			} else {
				List<String> messages = new ArrayList<String>();
				messages.add("アカウントが停止中です。");
				session.setAttribute("errorMessages", messages);
				response.sendRedirect("login");
			}
		} else {
			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}

	}
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		String loginid = request.getParameter("loginid");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		User user = loginService.login(loginid, password);

		if (user != null) {
			if (user.getIs_Stopped() != 1) {
				session.setAttribute("loginUser", user);
				response.sendRedirect("./");
			} else {
				List<String> messages = new ArrayList<String>();
				messages.add("アカウントが停止中です。");
				session.setAttribute("errorMessages", messages);
				response.sendRedirect("login");
			}
		} else {
			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}

	}
}

src/chapter6/controller/ManagementServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/management" })
public class ManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User user = (User) request.getSession().getAttribute("loginUser");

		if (user != null) {
			if (user.getPosition() == 1) {
				//ログインユーザー情報のidを元にDBからユーザー情報取得
				List<User> editUsers = new UserService().getUsers();

				request.setAttribute("editUsers", editUsers);

				request.getRequestDispatcher("management.jsp").forward(request, response);
			} else {
				messages.add("権限がないため、ページを開けません");
				session.setAttribute("errorMessages", messages);
				response.sendRedirect("./");
				return;
			}
		} else {
			response.sendRedirect("./");
		}
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User editAccount = getEditAccount(request);

		try {
			if (editAccount.getIs_Stopped() == 0) {
				new UserService().stop(editAccount);
			} else {
				new UserService().revival(editAccount);
			}

		} catch (NoRowsUpdatedRuntimeException e) {
			session.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("management.jsp").forward(request, response);
			return;
		}

		response.sendRedirect("management");
	}

	private User getEditAccount(HttpServletRequest request)
			throws IOException, ServletException {

		User editAccount = new User();
		editAccount.setId(Integer.parseInt(request.getParameter("id")));
		editAccount.setIs_Stopped(Integer.parseInt(request.getParameter("is_stopped")));

		return editAccount;
	}
}

src/chapter6/controller/SettingsServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User user = (User) request.getSession().getAttribute("loginUser");

		if (user != null) {
			if (user.getPosition() == 1) {
				//HttpSession session = request.getSession();
				//セッションよりログインユーザーの情報を取得
				//User loginUser = (User) session.getAttribute("loginUser");
				//ログインユーザー情報のidを元にDBからユーザー情報取得
				User editUser = new UserService().getUser(Integer.parseInt(request.getParameter("id")));
				request.setAttribute("editUser", editUser);

				List<User> editBranch = new UserService().getBranch();
				request.setAttribute("editBranch", editBranch);

				List<User> editPosition = new UserService().position();
				request.setAttribute("editPosition", editPosition);

				request.getRequestDispatcher("settings.jsp").forward(request, response);
			} else {
				session.setAttribute("errorMessages", messages);
				request.getRequestDispatcher("management.jsp").forward(request, response);
				return;
			}
		} else {
			response.sendRedirect("./");
		}
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User editUser = getEditUser(request);
		if (isValid(request, messages) == true) {

			try {
				if ((StringUtils.isEmpty(request.getParameter("password")))) {
					User editingUser = new UserService().getUser(Integer.parseInt(request.getParameter("id")));
					String brankpass = editingUser.getPassword();
					editUser.setPassword(brankpass);

					new UserService().passbrank(editUser);

				} else {

					new UserService().update(editUser);
				}

			} catch (NoRowsUpdatedRuntimeException e) {
				messages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
				session.setAttribute("errorMessages", messages);
				request.setAttribute("editUser", editUser);
				request.getRequestDispatcher("settings.jsp").forward(request, response);
				return;
			}

			session.setAttribute("loginid", editUser);
			response.sendRedirect("management");

		} else {
			session.setAttribute("errorMessages", messages);
			request.setAttribute("editUser", editUser);
			request.getRequestDispatcher("settings.jsp").forward(request, response);
		}
	}

	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setLoginid(request.getParameter("loginid"));
		editUser.setPassword(request.getParameter("password"));
		editUser.setName(request.getParameter("name"));
		editUser.setBranch(Integer.parseInt(request.getParameter("branchname")));
		editUser.setPosition(Integer.parseInt(request.getParameter("positionname")));
		return editUser;
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String loginid = request.getParameter("loginid");
		String password = request.getParameter("password");
		String checkpassword = request.getParameter("checkpassword");
		String name = request.getParameter("name");

		if (StringUtils.isEmpty(loginid) == true) {
			messages.add("ログインIDを入力してください");
		} else if (!(loginid.matches("^\\w{6,20}$"))) {
			messages.add("ログインIDは半角英数字6~20字で入力してください");
		}
		if (!(StringUtils.isEmpty(password))) {
			if (!(password.matches("^\\w{6,20}"))) {
				messages.add("パスワードは半角文字6~20字で入力してください");
			} else {
				if (StringUtils.isEmpty(checkpassword)) {
					messages.add("確認用パスワードを入力してください");
				} else {
					if (Integer.parseInt(password) != Integer.parseInt(checkpassword)) {
						messages.add("パスワードが違います");
					}
				}
			}
		}
		//データをすでに持たせているから、あとはsetするだけ

		if (StringUtils.isEmpty(name)) {
			messages.add("名前を入力してください");
		} else if (!(name.matches("^.{1,10}$"))) {
			messages.add("名前は10文字以内で入力してください");
		}
		// TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

WebContent/board.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>掲示板</title>
</head>
<body>

	<c:if test="${ not empty loginUser }">
		<div class="profile">
			<div class="name">
				<h2>
					新規投稿
				</h2>
			</div>
			<div class="loginid">
				ログインID：<c:out value="${loginUser.loginid}" />
			<div class="name">
				名前：<c:out value="${loginUser.name}" />
			</div><br>
			</div>
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="messages">
							<li><c:out value="${messages}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session" />
			</c:if>
		</div>
	</c:if>

	<div class="form-area">
		<c:if test="${ isShowMessageForm }">
			<form action="board" method="post">

				タイトル(30字以内)<br /> <input name="title"><br /> 本文（1000字以内）<br />
				<textarea name="message" cols="1000" class="tweet-box"></textarea>
				<br /> カテゴリー(10字以内)<br /> <input name="category"><br /> <input
					type="submit" value="投稿する">
			</form>
		</c:if>
	</div>

<!-- 	<div class="messages">
		<c:forEach items="${messages}" var="message">
			<div class="message">
				<div class="account-name">
					<span class="userid"><c:out value="${message.userid}" /></span>
					<span class="name"><c:out value="${loginUser.name}" /></span>
				</div>
				<div class="title">
					<c:out value="${message.title}" />
				</div>
				<div class="text">
					<c:out value="${message.text}" />
				</div>
				<div class="date">
					<fmt:formatDate value="${message.createdDate}"
						pattern="yyyy/MM/dd HH:mm:ss" />
				</div>
			</div>
		</c:forEach>
	</div>
	 -->
						<a href="./">ホーム</a>
	<div class="copyright">Copyright(c)MatsuuraTakehito</div>
</body>
</html>

WebContent/coment.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ログイン</title>
</head>
<body>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post">
			<br /> <label for="loginid">ログインID</label><br /> <input
				name="loginid" id="loginid" /> <br /> <label for="password">パスワード</label><br />
			<input name="password" type="password" id="password" /> <br />
			<input name="is_stopped" type="hidden" id="is_stopped" /> <br />
			 <input	type="submit" value="ログイン" /> <br /> <a href="./">戻る</a>
		</form>
		<div class="copyright">Copyright(c)YourName</div>
	</div>
</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ログイン</title>
</head>
<body>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post">
			<br /> <label for="loginid">ログインID</label><br /> <input
				name="loginid" id="loginid" /> <br /> <label for="password">パスワード</label><br />
			<input name="password" type="password" id="password" /> <br />
			<input name="is_stopped" type="hidden" id="is_stopped" /> <br />
			 <input	type="submit" value="ログイン" /> <br /> <a href="./">戻る</a>
		</form>
		<div class="copyright">Copyright(c)Matsuura Takehito</div>
	</div>
</body>
</html>

WebContent/management.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー管理画面</title>
</head>
<div class="header">
	ユーザー管理画面
	<c:if test="${ empty loginUser }">
		<a href="./">戻る</a>
	</c:if>

	<c:if test="${ not empty loginUser }">
		<div class="main-contents">
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session" />
			</c:if>
		</div>
		<c:if test="${ loginUser.position != 1 }">
		<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session" />
			</c:if>
		</c:if>
		<c:if test="${ loginUser.position == 1 }">
		<a href="signup">新規登録</a>
		<div class="userinfo">
			<div class="account-name">
				<table class="table" border="3" rules="all">
					<tr>
						<th>ログインID</th>
						<th>名前</th>
						<th>支店名</th>
						<th>部署・役職</th>
						<th>アカウントの停止・復活</th>
					</tr>
					<c:forEach items="${editUsers}" var="editUser">
						<tr>
							<th><span class="loginid"><c:out
										value="${editUser.loginid}" /></span></th>
							<th><a href="settings?id=${editUser.id}"><span
									class="name"><c:out value="${editUser.name}" /></span></a></th>
							<th><span class="branchname"><c:out
										value="${editUser.branchname}" /></span></th>
							<th><span class="positionname"><c:out
										value="${editUser.positionname}" /></span></th>

							<th><form method="post" action="management"	onSubmit="return checkSubmit()">
									<input name="id" value="${editUser.id}" id="id" type="hidden" />
									<span class="is_stopped"><input name="is_stopped"
										value="${editUser.is_Stopped}" type="hidden" /></span>
									<input type="submit" name="name"
										value="${editUser.statusChangeLabel}" onclick='return confirm("アカウントの状態を更新しますか？");'>
								</form> <br /></th>
						</tr>>
            </c:forEach>
				</table>
			</div>
		</div>
	</c:if>
	</c:if>
</div>

<br />
<a href="./">戻る</a>

<div class="copyright">Copyright(c)Matsuura_Takehito</div>

</body>
</html>

WebContent/settings.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>${loginUser.loginid}の設定</title>
<link href="css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="settings" method="post">
			<br /> <input name="id" value="${editUser.id}" id="id" type="hidden" />

			<label for="name">名前</label> <input name="name"
				value="${editUser.name}" id="name" />（名前はあなたの公開プロフィールに表示されます）<br />

			<label for="loginid">ログインID</label> <input name="loginid"
				value="${editUser.loginid}" /><br /> <label for="branch">支店名</label><br />


			<select name="branchname" id="branch">
				<c:forEach items="${editBranch}" var="editBranch">
					<option value="${editBranch.branchid}">${editBranch.branchname}</option>
				</c:forEach>
			</select> <br /> <label for="positionname">部署・役職</label><br /> <select
				name="positionname" id="position">
				<c:forEach items="${editPosition}" var="editPosition">
					<option value="${editPosition.positionid}">${editPosition.positionname}</option>
				</c:forEach>
			</select>


			<script>
				document.getElementById('branch').value = '${editUser.branch}';
				document.getElementById('position').value = '${editUser.position}';
			</script>
			<br /> <label for="password">パスワード</label> <input name="password"
				type="password" id="password" /> <br /> <label for="checkpassword">確認用パスワード</label>
			<input name="checkpassword" type="password" id="checkpassword" /> <br />
			<input type="submit" value="登録" /> <br /> <a href="management">戻る</a>
		</form>
		<div class="copyright">Copyright(c)Matsuura Takehito</div>
	</div>
</body>
</html>